#
#Thu Oct 02 10:44:37 EDT 2003
KeyStoreType=JCEKS
ListenerLog=0
RegistryType=daemon
RegistryPoolProcessTimeout=10
RegistryPoolTimeout=60
RegistryPoolSize=5
RegistryPath=
RegistryUser=
RegistryName=
JdbcUrl=
ListenerKeystore=LPnWMoqv/+Y\=
KeyStoreType=JCEKS
ServerFlag=0
RegistryPort=0
JVMArguments=
CLASSPATH=dmilistener.jar
JdbcDriverName=
ListenerName=daemon

# DaemonPort - port that the daemon listens on
# If modified, host node properties in SA Valet must be changed to match
DaemonPort=9000
DaemonHealthPort=0

# SecurityType - type of security used by daemon; valid types are:
#	NONE - no security
#	SSL - daemon requires SSL certificate
#	CLIENTSSL - both daemon and SA Valet require SSL certs
# If modified, host node properties in SA Valet must be changed to match
# Certificates MUST be set up before security is enabled
SecurityType=NONE
